# Generated by Django 4.2.2 on 2024-01-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_label', models.IntegerField(choices=[(0, 'Лайки'), (1, 'Лайки/Подписка/Комменатрий')], default=0, verbose_name='Тип Чата')),
                ('bot_chats', models.CharField(blank=True, max_length=150, verbose_name='Чат')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Чат ID')),
            ],
            options={
                'verbose_name_plural': 'Настройки Бота',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='ID Телеграм')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя')),
                ('status', models.IntegerField(choices=[(0, 'Обычный'), (1, 'VIP')], default=0, verbose_name='Статус')),
                ('vk_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ВК ID')),
                ('vk_user_url', models.URLField(blank=True, max_length=150, null=True, unique=True, verbose_name='Ссылка на ВК Профиль')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Являеться администратором?')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='LinksQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.CharField(max_length=255, verbose_name='ВК Ссылка')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подтверждения')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_queues', to='bot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Очередь ссылок',
            },
        ),
        migrations.CreateModel(
            name='VIPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_code', models.CharField(max_length=100, unique=True, verbose_name='VIP Код')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Действителен от')),
                ('bot_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_code', to='bot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'VIP Код',
                'verbose_name_plural': 'VIP Коды',
            },
        ),
        migrations.CreateModel(
            name='UserDoneLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='done_links', to='bot.botuser', verbose_name='Пользователь')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_by_user', to='bot.linksqueue', verbose_name='Выполненная ссылка')),
            ],
            options={
                'verbose_name_plural': 'Выполненные ссылки',
            },
        ),
        migrations.CreateModel(
            name='LinkStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.CharField(max_length=255, verbose_name='ВК Ссылка')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Ссылка подтверждена')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_links', to='bot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Хранилище ссылок',
            },
        ),
    ]
