# Generated by Django 4.2.2 on 2024-01-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='state_menu',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'VK_LINK'), (2, 'VIP_CODE'), (3, 'STATUS')], default=0, verbose_name='Состояние'),
        ),
    ]
