# Generated by Django 4.2.2 on 2024-01-30 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botuser_state_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipcode',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='vipcode',
            name='bot_user',
        ),
        migrations.AddField(
            model_name='botuser',
            name='vip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='bot.vipcode', verbose_name='VIP Код'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Является администратором?'),
        ),
    ]
