# Generated by Django 4.2.2 on 2024-02-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_taskstorage_chat_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='state_menu',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'VK_LINK'), (2, 'VIP_CODE'), (3, 'STATUS'), (3, 'RESET_LINK'), (3, 'ACCEPT_TASK_MANUALLY'), (3, 'GET_TASK_LINKS')], default=0, verbose_name='Состояние'),
        ),
    ]
