# Generated by Django 4.2.2 on 2024-03-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_linkstorage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksqueue',
            name='send_count',
            field=models.IntegerField(default=0, verbose_name='Текущее количество отправок'),
        ),
    ]
