# Generated by Django 4.2.2 on 2024-03-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_linksqueue_total_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotSettings',
            new_name='Chat',
        ),
    ]
