# Generated by Django 4.2.2 on 2024-03-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_botsettings_alter_chat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='link_count',
            field=models.IntegerField(default=0, verbose_name='Количество раздач ссылки'),
        ),
        migrations.AddField(
            model_name='chat',
            name='reply_link_count',
            field=models.IntegerField(default=0, verbose_name='Разрешена повторная отправка ссылки через: '),
        ),
    ]
