# Generated by Django 4.2.2 on 2024-03-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_linksqueue_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='mute',
            field=models.BooleanField(default=False, verbose_name='Блокировка чата'),
        ),
    ]
