# Generated by Django 4.2.2 on 2024-05-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_botuser_mute'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksqueue',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkstorage',
            name='comment',
            field=models.TextField(blank=True, default=None, verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
