# Generated by Django 4.2.2 on 2024-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_linksqueue_comment_alter_botuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksqueue',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='linkstorage',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
