# Generated by Django 4.2.2 on 2024-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_alter_linksqueue_comment_alter_linkstorage_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksqueue',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Ссылка подтверждена'),
        ),
        migrations.AddField(
            model_name='linksqueue',
            name='owner_id',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='ID Владельца'),
        ),
        migrations.AddField(
            model_name='linksqueue',
            name='post_id',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='ID Поста'),
        ),
    ]
