# Generated by Django 4.2.2 on 2024-05-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_linksqueue_is_approved_linksqueue_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksqueue',
            name='owner_id',
            field=models.BigIntegerField(default=0, verbose_name='ID Владельца'),
        ),
        migrations.AlterField(
            model_name='linksqueue',
            name='post_id',
            field=models.BigIntegerField(default=0, verbose_name='ID Поста'),
        ),
    ]
