# Generated by Django 4.2.2 on 2024-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_alter_linksqueue_options_alter_taskstorage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='bot_chats',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ссылка на группу'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_label',
            field=models.IntegerField(choices=[(0, 'Лайки'), (1, 'Лайки/Подписка/Комменатрий')], default=0, verbose_name='Тип группы'),
        ),
    ]
