# Generated by Django 4.2.2 on 2024-05-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_alter_chat_bot_chats_alter_chat_chat_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
