# Generated by Django 4.2.2 on 2024-05-08 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_alter_linksqueue_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstorage',
            name='chat_task',
        ),
        migrations.AddField(
            model_name='taskstorage',
            name='chat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_task_type', to='bot.chat', verbose_name='Тип чата'),
        ),
    ]
