# Generated by Django 4.2.2 on 2024-05-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_remove_taskstorage_chat_task_taskstorage_chat_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
