# Generated by Django 4.2.2 on 2024-05-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_alter_chat_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdonelinks',
            name='bot_user',
        ),
        migrations.RemoveField(
            model_name='userdonelinks',
            name='link',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='vip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='bot.vipcode'),
        ),
        migrations.AlterField(
            model_name='linksqueue',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_queues', to='bot.botuser'),
        ),
        migrations.AlterField(
            model_name='taskstorage',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_storage', to='bot.botuser'),
        ),
        migrations.DeleteModel(
            name='LinkStorage',
        ),
        migrations.DeleteModel(
            name='UserDoneLinks',
        ),
    ]
