# Generated by Django 4.2.2 on 2024-05-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_remove_userdonelinks_bot_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksqueue',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_queues', to='bot.botuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='taskstorage',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_storage', to='bot.botuser', verbose_name='Пользователь'),
        ),
    ]
