# Generated by Django 4.2.2 on 2024-05-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_alter_linksqueue_bot_user_alter_taskstorage_bot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='vip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='bot.vipcode', verbose_name='VIP Код'),
        ),
    ]
