# Generated by Django 4.2.2 on 2024-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_alter_botuser_vip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstorage',
            name='links',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_links', to='bot.linksqueue', verbose_name='Ссылки задания'),
        ),
    ]
