# Generated by Django 4.2.2 on 2024-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_taskstorage_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Текст сообщения',
                'verbose_name_plural': 'Тексты сообщений',
            },
        ),
    ]
