# Generated by Django 4.2.2 on 2024-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_messagetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Наименование'),
        ),
    ]
