# Generated by Django 4.2.2 on 2024-06-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_botsettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='name',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_text', to='bot.messagetext', verbose_name='Сообщения'),
        ),
    ]
