# Generated by Django 4.2.2 on 2024-06-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0038_remove_botsettings_name_botsettings_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='messages',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.botsettings'),
        ),
    ]
