# Generated by Django 4.2.2 on 2024-06-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_remove_botsettings_messages_botsettings_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.botsettings'),
        ),
    ]
