# Generated by Django 4.2.2 on 2024-06-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_chat_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='settings',
        ),
    ]
