# Generated by Django 4.2.2 on 2024-06-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_remove_chat_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsettings',
            options={'verbose_name': 'Настройки Бота', 'verbose_name_plural': 'Настройки Бота'},
        ),
    ]
