# Generated by Django 4.2.2 on 2024-06-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_messagelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'verbose_name': 'Логи Сообщений'},
        ),
    ]
