# Generated by Django 4.2.2 on 2024-06-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0047_delete_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstorage',
            name='task_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
