# Generated by Django 4.2.2 on 2024-06-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0048_taskstorage_task_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstorage',
            name='task_data',
        ),
    ]
