# Generated by Django 4.2.2 on 2024-06-19 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0050_messagelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_instance_log', to='bot.chat', verbose_name='Тип чата'),
        ),
    ]
