# Generated by Django 4.2.2 on 2024-07-02 01:24

from django.db import migrations


def add_message_texts(apps, schema_editor):
    BotSettings = apps.get_model('bot', 'BotSettings')
    MessageText = apps.get_model('bot', 'MessageText')

    bot_settings, created = BotSettings.objects.get_or_create(
        name='СИСТЕМНЫЕ НАСТРОЙКИ'
    )

    messages = [
        {"settings": bot_settings, "key": "START_MESSAGE", "message": "❤️Приветствую! Начнём с регистрации.\nУ вас есть ВИП код?\nДля приобретения ВИП статуса, чтобы не выполнять задания, вы можете написать @xxxxx"},
        {"settings": bot_settings, "key": "AUTH_USER", "message": "Воспользуйтесь меню"},
        {"settings": bot_settings, "key": "LINK_ENTER", "message": "➡️Пришлите адрес вашей личной страницы VK, с которой будете работать. \nМы будем проверять выполнение вами заданий по этой странице."},
        {"settings": bot_settings, "key": "VIP_CODE_ENTER", "message": "💎Введите ВИП код"},
        {"settings": bot_settings, "key": "VK_PAGE_ERROR", "message": "⛔️Упс! Что-то пошло не так (Проверьте правильность ссылки)"},
        {"settings": bot_settings, "key": "LINK_ERROR", "message": "⛔️Упс! Что-то пошло не так(\nПроверьте правильность ссылки"},
        {"settings": bot_settings, "key": "WRONG_FORMAT", "message": "Не верный формат запроса"},
        {"settings": bot_settings, "key": "WRONG_COMMAND", "message": "Неизвестная комманда"},
        {"settings": bot_settings, "key": "NO_VK_PAGE_IN_PROFILE", "message": "Вы не привязали рабочую VK страницу"},
        {"settings": bot_settings, "key": "VK_PAGE_ALREADY_EXSIST", "message": "Страница {vk_page_url} уже привязана к Вашему профилю"},
        {"settings": bot_settings, "key": "WRONG_URL_FORMAT", "message": "Некорректный формат ссылки"},
        {"settings": bot_settings, "key": "ONLY_ONE_LINK_TO_SEND", "message": "Можно отправить только одну ссылку за раз"},
        {"settings": bot_settings, "key": "WRONG_VIP_CODE", "message": "Неверный ВИП код"},
        {"settings": bot_settings, "key": "VIP_CODE_EXSISTS", "message": "У Вас уже есть Вип код"},
        {"settings": bot_settings, "key": "NO_CURRENT_TASK", "message": "Нет заданий"},
        {"settings": bot_settings, "key": "TASK_ACCEPTED_MANUALLY", "message": "Задание принято!"},
        {"settings": bot_settings, "key": "USER_TASK_NUMBER", "message": "Задание №"},
        {"settings": bot_settings, "key": "MEMBER_STATUS", "message": "Страница VK: {url}\nСтатус: {status}\nTelegram ID: {tg_id}"},
        {"settings": bot_settings, "key": "LINK_ADDED_FOR_NUMBER", "message": "Ваша ссылка: {link} добавлена в очередь под № {number}"},
        {"settings": bot_settings, "key": "TASK_IS_NOT_COMPLETE", "message": "Вы не завершили задание:\n\n{current_task}\n{links}"},
        {"settings": bot_settings, "key": "NO_TASKS_NOW", "message": "Сейчас нет заданий\n\nВаша ссылка добавлена в очередь под № {number}"},
        {"settings": bot_settings, "key": "COMMENT_MISSING", "message": "Отсутствует комментарий или его длина менее 5 слов"},
        {"settings": bot_settings, "key": "LIKE_MISSING", "message": "Отсутствует лайк"},
        {"settings": bot_settings, "key": "RESULT_MESSAGE", "message": "{value}"},
        {"settings": bot_settings, "key": "LINK_COUNT_ERROR", "message": "😢Не могу принять ссылку: {link}. От вашей предыдущей должно пройти {count} чужих ссылок. Осталось: {allow_links}"},
        {"settings": bot_settings, "key": "VK_PAGE_SUCCESS", "message": "✅Отлично! Теперь вы можете отправлять ссылки в чат"},
        {"settings": bot_settings, "key": "VIP_CODE_SUCCESS", "message": "✅Есть контакт! Срок действия кода - до <b>{vip_code_end_date}</b> г.\nТеперь ваши ссылки будут сразу попадать в очередь к другим участникам. \nВам не нужно самостоятельно выполнять задания."},
        {"settings": bot_settings, "key": "SUBSCRIBE_MISSING", "message": "Отсутсвтует подписка"},
    ]

    for message in messages:
        MessageText.objects.create(**message)


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0052_alter_linksqueue_bot_user_alter_taskstorage_bot_user'),
    ]

    operations = [
        migrations.RunPython(add_message_texts),
    ]
