# Generated by Django 4.2.2 on 2024-01-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.BigIntegerField(blank=True, unique=True, verbose_name='ID Vkontakte')),
                ('vk_page_url', models.URLField(blank=True, max_length=150, unique=True, verbose_name='VK page URL')),
            ],
            options={
                'verbose_name': 'Пользователь ВК',
                'verbose_name_plural': 'Пользователи ВК',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='ID Telegram')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('status', models.IntegerField(choices=[(0, 'Неизвестно'), (1, 'Обычный'), (2, 'VIP')], default=0, verbose_name='User status')),
                ('vip_code', models.CharField(blank=True, max_length=100, verbose_name='VIP code')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('vk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.vkuser', verbose_name='Linked VK User')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
    ]
