# Generated by Django 4.2.2 on 2024-02-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_vipcode_added_at_remove_vipcode_bot_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksqueue',
            name='link_priority',
            field=models.BooleanField(default=False, verbose_name='Приоритет ссылки'),
        ),
        migrations.AddField(
            model_name='linksqueue',
            name='queue_number',
            field=models.CharField(default='0000001', max_length=10, unique=True, verbose_name='Номер в очереди'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код задания')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_storage', to='bot.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Хранилище заданий',
            },
        ),
    ]
