# Generated by Django 4.2.2 on 2024-02-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_botuser_vip_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstorage',
            name='chat_task',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наименовании группы'),
        ),
    ]
