# Generated by Django 4.2.2 on 2024-02-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_linkstorage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstorage',
            name='order_number',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
