# Generated by Django 4.2.2 on 2024-03-04 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_taskstorage_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkstorage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
