# Generated by Django 4.2.2 on 2024-03-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_linksqueue_send_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksqueue',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='Количество отправок ссылки'),
        ),
    ]
