# Generated by Django 4.2.2 on 2024-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_chat_link_count_chat_reply_link_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='task_link_count',
            field=models.IntegerField(default=0, verbose_name='Количество ссылок в задании'),
        ),
    ]
