# Generated by Django 4.2.2 on 2024-03-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_chat_task_link_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkstorage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='linkstorage',
            name='chat_type',
            field=models.CharField(default='', max_length=10, verbose_name='Тип чата'),
            preserve_default=False,
        ),
    ]
